FROM 111664719423.dkr.ecr.us-east-1.amazonaws.com/base:latest@sha256:28a55bcea40ea09c63e8d01c44b76156a222b93c2abd8148bca16d9ebf48b5e8
ARG REVISION
ARG SOURCE
LABEL org.opencontainers.image.revision=$REVISION
LABEL org.opencontainers.image.source=$SOURCE
CMD ["cat", "dog.json"]

