FROM 111664719423.dkr.ecr.us-east-1.amazonaws.com/base:latest@sha256:a6915ebd16227ce2cc8708150f3d1bff1b968eebcfbd0112382560112854ab46
ARG REVISION
ARG SOURCE
LABEL org.opencontainers.image.revision=$REVISION
LABEL org.opencontainers.image.source=$SOURCE
CMD ["cat", "dog.json"]

