FROM 111664719423.dkr.ecr.us-east-1.amazonaws.com/base:latest@sha256:3370d47a21ffd2eb6568a2e821bd02cd5a84341e27c27cb70fdecb921ae19db9
ARG REVISION
ARG SOURCE
LABEL org.opencontainers.image.revision=$REVISION
LABEL org.opencontainers.image.source=$SOURCE
CMD ["cat", "dog.json"]

